language: bash
services: docker
before_install:
  - cd src/main/docker/test
  - echo "We are in the Docker folder !!!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push elderpereira/rest-with-springboot2-elder:latest
  on:
    branch: main
notifications:
  email: false