version: '3.1'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_test
    ports:
    - 3307:3306
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - mysql-network
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
    - 8081:8080
    networks:
    - mysql-network
    
volumes:
  mysql_data:
  
networks:
  mysql-network:
    driver: bridge